-- SCHEMA PARA ALUMBRAR: CAMINO A UCDM
-- Copia y pega este SQL en el Editor SQL de tu dashboard de Supabase.

-- TABLA DE GEMAS (Opcional, si quieres editarlas desde la DB)
create table public.gemas (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  phrase text not null,
  idea text not null,
  action text not null,
  mantra text not null,
  category text not null
);

-- TABLA DE FAVORITOS (Para que los usuarios guarden sus gemas)
create table public.user_favorites (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users not null,
  gema_id bigint references public.gemas,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- TABLA DE SESIONES DE CHAT
create table public.chat_sessions (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users not null,
  title text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- TABLA DE MENSAJES DE CHAT
create table public.chat_messages (
  id uuid default gen_random_uuid() primary key,
  session_id uuid references public.chat_sessions on delete cascade not null,
  role text not null check (role in ('user', 'model')),
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- TABLA DE SUSCRIPCIONES
create table public.subscriptions (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users not null unique,
  status text not null check (status in ('active', 'canceled', 'incomplete')),
  plan_id text not null,
  current_period_end timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar Row Level Security (RLS)
alter table public.user_favorites enable row level security;
alter table public.chat_sessions enable row level security;
alter table public.chat_messages enable row level security;
alter table public.subscriptions enable row level security;

-- Políticas de Seguridad (Solo el dueño puede ver/editar sus datos)

-- Favoritos
create policy "Users can view their own favorites" on public.user_favorites
  for select using (auth.uid() = user_id);

create policy "Users can insert their own favorites" on public.user_favorites
  for insert with check (auth.uid() = user_id);

create policy "Users can delete their own favorites" on public.user_favorites
  for delete using (auth.uid() = user_id);

-- Sesiones
create policy "Users can view their own sessions" on public.chat_sessions
  for select using (auth.uid() = user_id);

create policy "Users can insert their own sessions" on public.chat_sessions
  for insert with check (auth.uid() = user_id);

-- Mensajes
create policy "Users can view messages from their sessions" on public.chat_messages
  for select using (
    exists (
      select 1 from public.chat_sessions
      where id = chat_messages.session_id
      and user_id = auth.uid()
    )
  );

create policy "Users can insert messages to their sessions" on public.chat_messages
  for insert with check (
    exists (
      select 1 from public.chat_sessions
      where id = chat_messages.session_id
      and user_id = auth.uid()
    )
  );

-- Suscripciones
create policy "Users can view their own subscription" on public.subscriptions
  for select using (auth.uid() = user_id);
