# Supabase Schema for "Alumbrar"

Copia y pega este SQL en el Editor SQL de tu dashboard de Supabase para crear las tablas necesarias.

```sql
-- TABLA DE GEMAS (Opcional, si quieres editarlas desde la DB)
create table public.gemas (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  phrase text not null,
  idea text not null,
  action text not null,
  mantra text not null,
  category text not null
);

-- TABLA DE FAVORITOS (Para que los usuarios guarden sus gemas)
create table public.user_favorites (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users not null,
  gema_id bigint references public.gemas,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- TABLA DE HISTORIAL DE CHAT
create table public.chat_sessions (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users not null,
  title text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public.chat_messages (
  id uuid default gen_random_uuid() primary key,
  session_id uuid references public.chat_sessions on delete cascade not null,
  role text not null check (role in ('user', 'model')),
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar Row Level Security (RLS)
alter table public.user_favorites enable row level security;
alter table public.chat_sessions enable row level security;
alter table public.chat_messages enable row level security;

-- Políticas de Seguridad (Solo el dueño puede ver/editar sus datos)
create policy "Users can view their own favorites" on public.user_favorites
  for select using (auth.uid() = user_id);

create policy "Users can insert their own favorites" on public.user_favorites
  for insert with check (auth.uid() = user_id);

create policy "Users can delete their own favorites" on public.user_favorites
  for delete using (auth.uid() = user_id);
```
